[package]
name = "rust_bpmn_analyzer"
version = "2.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
colored = "3.1.1"
quick-xml = { version = "0.39.2" }

[dev-dependencies]
rstest = "0.26.1"
