[package]
name = "rust_bpmn_analyzer"
version = "2.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
colored = "3.0.0"
quick-xml = { version = "0.39.0" }

[dev-dependencies]
rstest = "0.26.1"
